Setting up .git/hooks/pre-commit to encourage release incrementation

diff --git a/TODO b/TODO
--- a/TODO
+++ b/TODO
@@ -1,3 +1,24 @@
+----------------------------------------------
+save .git/hooks/pre-commit
+#!/bin/bash
+
+FILE=release_version.h
+
+CUR_NUM=`git show HEAD:./release_version.h | awk '{print $3}' | sed 's/"//g'`
+
+NEW_NUM=`cat ./release_version.h | awk '{print $3}' | sed 's/"//g'`
+
+if [ $NEW_NUM -le $CUR_NUM ]; then
+    echo '***********************************************************************'
+    echo 'Failure: increment RELEASE_VERSION before committing (release_version.h)'
+    echo '         do `git commit --no-verify` to skip this check and commit anyway'
+    echo '***********************************************************************'
+    exit 1
+fi
+
+exit 0
+----------------------------------------------
+
 NEW TODO 2018-12-07
 
 
